app:
  endpoints:
    catalog: http://catalog.retail-app.svc.cluster.local:80
    carts: http://cart-carts.retail-app.svc.cluster.local:80
    checkout: http://checkout.retail-app.svc.cluster.local:80
    orders: http://orders.retail-app.svc.cluster.local:80
